export const SAMPLE_DATA = [
  {
    id: "bd_1",
    serialNumber: 1,
    bd: "RFP",
    quarter: "Q1",
    client: "Multi-lateral Development Bank",
    organization: "World Bank",
    title: "Energy surveys in Refugee Camps in Ethiopia",
    businessLine: "Energy",
    serviceOffering: "Data Collection and analysis",
    typeBD: "Core(Continuity)",
    country: "Ethiopia",
    origin: "Direct from client",
    deadline: "",
    cvsProfiles: "AK",
    workplanBudget: "PA",
    methodology: "",
    otherActivity: "",
    partners: "Ethio Resource Group (ERG)",
    pc: "TS",
    pd: "JI",
    budget: 250000,
    status: "Under development",
    timeframe: "",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_2",
    serialNumber: 2,
    bd: "RFP",
    quarter: "Q1",
    client: "Development Agency",
    organization: "UNOPS",
    title:
      "Request for Proposal for Consultancy Services to Conduct Market Assessment and Develop a Roadmap for SEforALL Powering Healthcare Programme in Democratic Republic of Congo",
    businessLine: "Energy",
    serviceOffering: "Core(Continuity)",
    typeBD: "Core(Continuity)",
    country: "Democratic Republic of Congo",
    origin: "From Dev Aid",
    deadline: "2/24/2025",
    cvsProfiles: "AA",
    workplanBudget: "IM",
    methodology: "CM",
    otherActivity: "WM",
    partners: "Halo Sarl",
    pc: "AK",
    pd: "MK",
    budget: 196830.79,
    status: "Submitted",
    timeframe: "7",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_3",
    serialNumber: 3,
    bd: "RFP",
    quarter: "Q1",
    client: "Multi-lateral Development Bank",
    organization: "AfDB",
    title: "Developing Malawi Clean Cooking Strategy",
    businessLine: "Energy (Cooking)",
    serviceOffering: "Program Design",
    typeBD: "Core(Continuity)",
    country: "Malawi",
    origin: "BD search(Other sources other than DevAid)",
    deadline: "2/25/2025",
    cvsProfiles: "MeK",
    workplanBudget: "AK",
    methodology: "AO",
    otherActivity: "",
    partners: "Community Energy Malawi, Margaret Matinda",
    pc: "MeK",
    pd: "TS",
    budget: 172056.86,
    status: "Won",
    timeframe: "12",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_4",
    serialNumber: 4,
    bd: "RFP",
    quarter: "Q1",
    client: "Development Agency",
    organization: "Energy for Savings Trust",
    title: "Consultancy Services to support research assessing the role of early stage support to PUE companies",
    businessLine: "Energy",
    serviceOffering: "Technical Assistance",
    typeBD: "Core(Continuity)",
    country: "Kenya",
    origin: "From partner",
    deadline: "6/3/2025",
    cvsProfiles: "AA",
    workplanBudget: "WM",
    methodology: "CN",
    otherActivity: "",
    partners: "Dr. Ben Robinson",
    pc: "MeK",
    pd: "MK",
    budget: 79473,
    status: "Lost",
    timeframe: "7",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_5",
    serialNumber: 5,
    bd: "RFP",
    quarter: "Q1",
    client: "Development Agency",
    organization: "UK PACT",
    title: "Project 3: Technical support for integrated energy planning",
    businessLine: "Energy",
    serviceOffering: "Technical Assistance",
    typeBD: "Adjacent (Change)",
    country: "Kenya",
    origin: "BD search(Other sources other than DevAid)",
    deadline: "1/29/2025",
    cvsProfiles: "IM",
    workplanBudget: "WM",
    methodology: "MB",
    otherActivity: "",
    partners: "UCL – University College London",
    pc: "AA",
    pd: "MB",
    budget: 986970,
    status: "Submitted",
    timeframe: "12",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_6",
    serialNumber: 40,
    bd: "EOI",
    quarter: "Q1",
    client: "Multi-lateral Development Bank",
    organization: "World Bank",
    title: "National Energy Surveys in Nigeria and Liberia",
    businessLine: "Energy",
    serviceOffering: "Data Collection and analysis",
    typeBD: "Core(Continuity)",
    country: "Liberia and Nigeria",
    origin: "BD search(Other sources other than DevAid)",
    deadline: "1/27/2025",
    cvsProfiles: "IM",
    workplanBudget: "IM",
    methodology: "AK",
    otherActivity: "",
    partners: "The Khana Group (TKG)",
    pc: "AK",
    pd: "JI",
    budget: 0,
    status: "Shortlisted",
    timeframe: "7",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_7",
    serialNumber: 41,
    bd: "EOI",
    quarter: "Q1",
    client: "Multi-lateral Development Bank",
    organization: "AfDB",
    title: "Management of the Africa Energy Portal",
    businessLine: "Energy",
    serviceOffering: "Technical Assistance",
    typeBD: "Core(Continuity)",
    country: "African Countries",
    origin: "From Dev Aid",
    deadline: "2/21/2025",
    cvsProfiles: "IM",
    workplanBudget: "IM",
    methodology: "IG",
    otherActivity: "AA",
    partners: "",
    pc: "CM",
    pd: "",
    budget: 0,
    status: "Submitted",
    timeframe: "",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_8",
    serialNumber: 22,
    bd: "RFP",
    quarter: "Q2",
    client: "Development Agency",
    organization: "UK PACT",
    title: "Project 2: Accelerating clean cooking adoption: A data-driven approach and capacity building",
    businessLine: "Energy (Cooking)",
    serviceOffering: "Research and Data Analytics",
    typeBD: "Core(Continuity)",
    country: "Kenya",
    origin: "BD search(Other sources other than DevAid)",
    deadline: "1/29/2025",
    cvsProfiles: "IM",
    workplanBudget: "IC",
    methodology: "RG",
    otherActivity: "",
    partners: "SEI and Burn Lab",
    pc: "RG",
    pd: "DW",
    budget: 957668,
    status: "Lost",
    timeframe: "24",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_9",
    serialNumber: 48,
    bd: "EOI",
    quarter: "Q2",
    client: "Multi-lateral Development Bank",
    organization: "World Bank",
    title: "Market Assessment of Productive Uses of Renewable Energy (PURE)",
    businessLine: "Energy (PUE)",
    serviceOffering: "Data Collection and analysis",
    typeBD: "Core(Continuity)",
    country: "COMESA Countries",
    origin: "Direct from client",
    deadline: "4/14/2025",
    cvsProfiles: "MeK",
    workplanBudget: "MeK",
    methodology: "",
    otherActivity: "",
    partners: "GOGLA , CLASP",
    pc: "AA",
    pd: "MK",
    budget: 0,
    status: "Submitted",
    timeframe: "12",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bd_10",
    serialNumber: 12,
    bd: "RFP",
    quarter: "Q1",
    client: "Other",
    organization: "Global Alliance for Improved Nutrition (GAIN)",
    title:
      "Household level preparedness to food security & climate shocks and develop inclusive contingency plans to respond to economic and climate-related shocks, with gender lens In Nairobi, Nakuru, & Nyandarua counties",
    businessLine: "Climate change",
    serviceOffering: "Research and Data Analytics",
    typeBD: "New (Disruptive)",
    country: "Kenya",
    origin: "BD search(Other sources other than DevAid)",
    deadline: "3/23/2025",
    cvsProfiles: "MaK",
    workplanBudget: "IM",
    methodology: "PA",
    otherActivity: "",
    partners: "Keni Kariuki",
    pc: "MaK",
    pd: "EO",
    budget: 106326.93,
    status: "Submitted",
    timeframe: "6",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
